class Actions {
  static const PING = "PING",
      PONG = "PONG",
//
      ERROR = "ERROR",
//
      LOGIN_ANONYMOUS = "LOGIN_ANONYMOUS",
      LOGIN_GOOGLE = "LOGIN_GOOGLE",
//
      LOGOUT = "LOGOUT",
//
      LIST_CHAT_ROOMS = "LIST_CHAT_ROOMS",
      LIST_ACCESSIBLE_CHAT_ROOMS = "LIST_ACCESSIBLE_CHAT_ROOMS",
      GET_CHAT_MESSAGES = "GET_CHAT_MESSAGES",
      GET_CHAT_FILES = "GET_CHAT_FILES",
      JOIN_CHAT_ROOM = "JOIN_CHAT_ROOM",
      LEAVE_CHAT_ROOM = "LEAVE_CHAT_ROOM",
      ADD_CHAT_MESSAGE = "ADD_CHAT_MESSAGE",
      ADD_CHAT_FILE = "ADD_CHAT_FILE",
      CREATE_CHAT_ROOM = "CREATE_CHAT_ROOM",
      ADD_CHAT_ROOM = "ADD_CHAT_ROOM",
      REMOVE_CHAT_ROOM = "REMOVE_CHAT_ROOM",
      UNLOCK_CHAT_ROOM = "UNLOCK_CHAT_ROOM",
//
      CHANGE_ANONYMOUS_NAME = "CHANGE_ANONYMOUS_NAME",
//
      START_FILE_UPLOAD = "START_FILE_UPLOAD",
      UPLOAD_FILE = "UPLOAD_FILE",
      GET_FILE = "GET_FILE",
      GET_FILE_META = "GET_FILE_META";
}
